version: '3.7'

services:
  nginx:
    container_name: refactoring-nginx
    image: nginx:alpine
    volumes:
      - ./:/usr/share/www/html:delegated # declare that the host's www folder contents will mount the html folder of container
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf # copy an nginx configuration to server container and replace the default
    ports:
      - 8123:80
    environment:
      - NGINX_HOST=${NGINX_HOST}
    depends_on:
      - "php"
  php:
    container_name: refactoring-php
    image: phpdockerio/php74-fpm
    working_dir: /usr/share/www/html
    depends_on:
      - "db"
    volumes:
      - ./:/usr/share/www/html:delegated
  db:
    container_name: refactoring-db
    image: mariadb:10.5.9
    volumes:
      - db-data:/var/lib/mysql # when docker-compose down is used and then docker-compose up -d the database will not be affected
    environment:
      - MYSQL_DATABASE=refactoring_test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root

volumes:
  db-data: